/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2021-11-16 02:14:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class toolbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  ///////////////////////// JSTL  ////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ToolBar Start /////////////////////////////////////-->\r\n");
      out.write("<div class=\"navbar  navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t       \r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/index.jsp\">Model2 MVC Shop</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- toolBar Button Start //////////////////////// -->\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t    <button class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#target\">\r\n");
      out.write("\t\t        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t        <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- toolBar Button End //////////////////////// -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <!--  dropdown hover Start -->\r\n");
      out.write("\t\t<div \tclass=\"collapse navbar-collapse\" id=\"target\" \r\n");
      out.write("\t       \t\t\tdata-hover=\"dropdown\" data-animations=\"fadeInDownNew fadeInRightNew fadeInUpNew fadeInLeftNew\">\r\n");
      out.write("\t         \r\n");
      out.write("\t         \t<!-- Tool Bar 를 다양하게 사용하면.... -->\r\n");
      out.write("\t             <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t             \r\n");
      out.write("\t              <!--  회원관리 DrowDown -->\r\n");
      out.write("\t              <li class=\"dropdown\">\r\n");
      out.write("\t                     <a  href=\"#####\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("\t                         <span >회원관리</span>\r\n");
      out.write("\t                         <span class=\"caret\"></span>\r\n");
      out.write("\t                     </a>\r\n");
      out.write("\t                     <ul class=\"dropdown-menu\">\r\n");
      out.write("\t                         <li><a href=\"#\">개인정보조회</a></li>\r\n");
      out.write("\t                         \r\n");
      out.write("\t                         ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t                         \r\n");
      out.write("\t                         <li class=\"divider\"></li>\r\n");
      out.write("\t                         <li><a href=\"#\">etc...</a></li>\r\n");
      out.write("\t                     </ul>\r\n");
      out.write("\t                 </li>\r\n");
      out.write("\t                 \r\n");
      out.write("\t              <!-- 판매상품관리 DrowDown  -->\r\n");
      out.write("\t               ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t                 \r\n");
      out.write("\t              <!-- 구매관리 DrowDown -->\r\n");
      out.write("\t              <li class=\"dropdown\">\r\n");
      out.write("\t                     <a  href=\"#####\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("\t                         <span >상품구매</span>\r\n");
      out.write("\t                         <span class=\"caret\"></span>\r\n");
      out.write("\t                     </a>\r\n");
      out.write("\t                     <ul class=\"dropdown-menu\">\r\n");
      out.write("\t                         <li><a href=\"#\">상 품 검 색</a></li>\r\n");
      out.write("\t                         \r\n");
      out.write("\t                         ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t                         \r\n");
      out.write("\t                         <li><a href=\"#\">최근본상품</a></li>\r\n");
      out.write("\t                         <li class=\"divider\"></li>\r\n");
      out.write("\t                         <li><a href=\"#####\">etc..</a></li>\r\n");
      out.write("\t                     </ul>\r\n");
      out.write("\t                 </li>\r\n");
      out.write("\t                 \r\n");
      out.write("\t                 <li><a href=\"#####\">etc...</a></li>\r\n");
      out.write("\t             </ul>\r\n");
      out.write("\t             \r\n");
      out.write("\t             <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t                <li><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- dropdown hover END -->\t       \r\n");
      out.write("\t    \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t<!-- ToolBar End /////////////////////////////////////-->\r\n");
      out.write(" \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t//============= logout Event  처리 =============\t\r\n");
      out.write("\t\t $(function() {\r\n");
      out.write("\t\t\t//==> DOM Object GET 3가지 방법 ==> 1. $(tagName) : 2.(#id) : 3.$(.className)\r\n");
      out.write("\t\t \t$(\"a:contains('로그아웃')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t$(self.location).attr(\"href\",\"/user/logout\");\r\n");
      out.write("\t\t\t\t//self.location = \"/user/logout\"\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//============= 회원정보조회 Event  처리 =============\t\r\n");
      out.write("\t\t $(function() {\r\n");
      out.write("\t\t\t//==> DOM Object GET 3가지 방법 ==> 1. $(tagName) : 2.(#id) : 3.$(.className)\r\n");
      out.write("\t\t \t$(\"a:contains('회원정보조회')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t//$(self.location).attr(\"href\",\"/user/logout\");\r\n");
      out.write("\t\t\t\tself.location = \"/user/listUser\"\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//=============  개인정보조회회 Event  처리 =============\t\r\n");
      out.write("\t\t \t$( \"a:contains('개인정보조회')\" ).on(\"click\" , function() {\r\n");
      out.write("\t\t \t\t//==> DOM Object GET 3가지 방법 ==> 1. $(tagName) : 2.(#id) : 3.$(.className)\r\n");
      out.write("\t\t\t\t$(self.location).attr(\"href\",\"/user/getUser?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//============= 상품/구매 관련 Event  처리 =============\t\r\n");
      out.write("\t\t $(function() {\r\n");
      out.write("\t\t\t\t//==> DOM Object GET 3가지 방법 ==> 1. $(tagName) : 2.(#id) : 3.$(.className)\r\n");
      out.write("\t\t\t \t$(\"a:contains('판매상품등록')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t\t//$(self.location).attr(\"href\",\"/user/logout\");\r\n");
      out.write("\t\t\t\t\tself.location = \"../product/addProductView.jsp\"\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$( \"a:contains('판매상품관리')\" ).on(\"click\" , function() {\r\n");
      out.write("\t\t\t \t\tself.location = \"/product/listProduct?menu=manage\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t \t$(\"a:contains('상 품 검 색')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t\tself.location = \"/product/listProduct?menu=search\"\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t \t$(\"a:contains('구매이력조회')\").on(\"click\" , function() {\r\n");
      out.write("\t\t\t\t\tself.location = \"/purchase/listPurchase\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$( \"a:contains('최근본상품')\" ).on(\"click\" , function() {\r\n");
      out.write("\t\t\t \t\tself.location = \"../history.jsp\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t</script>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /layout/toolbar.jsp(42,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.role == 'admin'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t                         \t<li><a href=\"#\">회원정보조회</a></li>\r\n");
        out.write("\t                         ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /layout/toolbar.jsp(52,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.role == 'admin'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t              <li class=\"dropdown\">\r\n");
        out.write("\t\t                     <a  href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">\r\n");
        out.write("\t\t                         <span >판매상품관리</span>\r\n");
        out.write("\t\t                         <span class=\"caret\"></span>\r\n");
        out.write("\t\t                     </a>\r\n");
        out.write("\t\t                     <ul class=\"dropdown-menu\">\r\n");
        out.write("\t\t                         <li><a href=\"#\">판매상품등록</a></li>\r\n");
        out.write("\t\t                         <li><a href=\"#\">판매상품관리</a></li>\r\n");
        out.write("\t\t                         <li class=\"divider\"></li>\r\n");
        out.write("\t\t                         <li><a href=\"#\">etc..</a></li>\r\n");
        out.write("\t\t                     </ul>\r\n");
        out.write("\t\t                </li>\r\n");
        out.write("\t                 ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /layout/toolbar.jsp(76,26) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.role == 'user'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t                           <li><a href=\"#\">구매이력조회</a></li>\r\n");
        out.write("\t                         ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
