/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2021-11-16 02:14:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  ///////////////////////// JSTL  ////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"EUC-KR\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!--   jQuery , Bootstrap CDN  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" >\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap Dropdown Hover CSS -->\r\n");
      out.write("   <link href=\"/css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   <link href=\"/css/bootstrap-dropdownhover.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("    <!-- Bootstrap Dropdown Hover JS -->\r\n");
      out.write("   <script src=\"/javascript/bootstrap-dropdownhover.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  CSS 추가 : 툴바에 화면 가리는 현상 해결 :  주석처리 전, 후 확인-->\r\n");
      out.write("\t<style>\r\n");
      out.write("        body {\r\n");
      out.write("            padding-top : 70px;\r\n");
      out.write("        }\r\n");
      out.write("   \t</style>\r\n");
      out.write("   \t\r\n");
      out.write("     <!--  ///////////////////////// JavaScript ////////////////////////// -->\r\n");
      out.write("\t \t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ToolBar Start /////////////////////////////////////-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/toolbar.jsp", out, false);
      out.write("\r\n");
      out.write("   \t<!-- ToolBar End /////////////////////////////////////-->\r\n");
      out.write("\r\n");
      out.write("\t<!--  아래의 내용은 http://getbootstrap.com/getting-started/  참조 -->\t\r\n");
      out.write("   \t<div class=\"container \">\r\n");
      out.write("      <!-- Main jumbotron for a primary marketing message or call to action -->\r\n");
      out.write("      <div class=\"jumbotron\">\r\n");
      out.write("        <h1>Model2MVCShop </h1>\r\n");
      out.write("        <p>J2SE , DBMS ,JDBC , Servlet & JSP, Java Framework , HTML5 , UI Framework 학습 후 Mini-Project 진행</p>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 참조 : http://getbootstrap.com/css/   : container part..... -->\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("        <h1><img src=\"/images/uploadFiles/162395238656411.jpg\"></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
